travis:
  secure:
    BINSTAR_TOKEN: L1Z2gXr+6+IqRCpAcCPYaP6ZCpywUG2p0io6JRR3E3/YSHsnXBt58Giv3IhWWphYpuUuU5NdUzeZvkRl68pLDgCTDxA3HSNMZJsYbPV75lv+sfHn6LCURNMB1OuF+vpG567MjtwBvU/3s2LN2K5RjLqZhVpl09t5mDPZtnfci4BouInUL4CS+DhWJZS6I/luLeLPSCXYBrw5UN4sCBicJIB+nxNuLy5lY7s8Wfzd7HrHX4H1X7ZJKTDtzz9ryRk/8u885xlAwvQWU91RTmBXlO05h/ENsUzHtTEcfwgOnLls/2yLkERcdSgEpkFfz4uoPthiU+34OIxSA6FmM5sPA848TQ4L2pzOROTTwy02tPVWxoU+5FnVhWr5Pain2fuIJ8bhYmkRCax31sqWCJUm9DXVuRi46QrjnDcASFnTTPl6IuD6Mi7JBPYqc5OCONq5Xjzw5SnPmV0dHSP9wyIfQQqixA/s5VmG3ksgQbpyY1OVCr+jSvwvJ/xs83kzZMAOBliVCks60571i1mTvkqIVBuPbC0gKX35Q0Ikb4h0HPF59IQcBsKjNtsJfn3VtuqYeh9a4TP5S1fuKK2cSWjvTgiRQ1yRFbO7wkOS4CHMWGUwW90f8RIrGmCeP6C1hmPfTcmtrwKR++Gx4KaFDdavD64HlvFAhiFhu3jSpATm5ac=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
